"""default use root user

Revision ID: 41d55e8db5e8
Revises: 5a25f1dd381e
Create Date: 2016-12-03 20:13:30.928549

"""

# revision identifiers, used by Alembic.
revision = '41d55e8db5e8'
down_revision = '5a25f1dd381e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
